export default [
  {itemLevel: 1, name: "Blue Pearl"},
  {itemLevel: 1, name: "Dagger"},
  {itemLevel: 1, name: "Food"},
  {itemLevel: 1, name: "Staff"},
  {itemLevel: 1, name: "White Pearl"},
  {itemLevel: 2, name: "Amulet Detect Evil"},
  {itemLevel: 2, name: "Healing Potion"},
  {itemLevel: 2, name: "Leather Armor"},
  {itemLevel: 2, name: "Leather Gloves"},
  {itemLevel: 2, name: "Mace"},
  {itemLevel: 2, name: "Small Shield"},
  {itemLevel: 2, name: "Throwing Star"},
  {itemLevel: 3, name: "Axe"},
  {itemLevel: 3, name: "Club"},
  {itemLevel: 3, name: "Studded Leather"},
  {itemLevel: 3, name: "Sword"},
  {itemLevel: 3, name: "Velocitas Potion"},
  {itemLevel: 4, name: "Battle Axe"},
  {itemLevel: 4, name: "Chain Hood"},
  {itemLevel: 4, name: "Elven Dagger"},
  {itemLevel: 4, name: "Long Sword"},
  {itemLevel: 4, name: "Potion of Curing"},
  {itemLevel: 4, name: "Two Handed Sword"},
  {itemLevel: 5, name: "Apprentice Magic Staff"},
  {itemLevel: 5, name: "Battle Scroll"},
  {itemLevel: 5, name: "Chain Gloves"},
  {itemLevel: 5, name: "Chain Mail"},
  {itemLevel: 5, name: "Greater Health Potion (craftable)"},
  {itemLevel: 5, name: "Iron Shield"},
  {itemLevel: 5, name: "Large Shield"},
  {itemLevel: 5, name: "Powerful Health Potion (craftable? buyable at mystic merchant)"},
  {itemLevel: 5, name: "Short Sword"},
  {itemLevel: 6, name: "Elven Leather"},
  {itemLevel: 6, name: "Halberd"},
  {itemLevel: 6, name: "Iron Helmet"},
  {itemLevel: 6, name: "Long Bow"},
  {itemLevel: 6, name: "Pine Shaft Arroows"},
  {itemLevel: 6, name: "Spiked Mace"},
  {itemLevel: 7, name: "Apprentice Robe"},
  {itemLevel: 7, name: "Battle Hammer"},
  {itemLevel: 7, name: "Elven Leather Gloves"},
  {itemLevel: 7, name: "Silver Axe"},
  {itemLevel: 7, name: "Silver Mace"},
  {itemLevel: 7, name: "Silver Short Sword"},
  {itemLevel: 7, name: "Silver Sword"},
  {itemLevel: 7, name: "War Hammer"},
  {itemLevel: 8, name: "Dragon Claw"},
  {itemLevel: 8, name: "Elven Chain Gloves"},
  {itemLevel: 8, name: "Magic Throwing Star"},
  {itemLevel: 8, name: "Plate Mail"},
  {itemLevel: 8, name: "Rage Potion"},
  {itemLevel: 8, name: "Rapier"},
  {itemLevel: 8, name: "Sensus Scroll"},
  {itemLevel: 9, name: "Elven Chain"},
  {itemLevel: 9, name: "Elven Long Bow"},
  {itemLevel: 9, name: "Life Saving Amulet"},
  {itemLevel: 9, name: "Magic Dagger"},
  {itemLevel: 9, name: "Magic Helmet"},
  {itemLevel: 9, name: "Magic Shield"},
  {itemLevel: 9, name: "Magic Staff"},
  {itemLevel: 10, name: "Apprentice Hat"},
  {itemLevel: 10, name: "Magic Chain Gloves"},
  {itemLevel: 10, name: "Magic Chain Gloves (super??? no pic yet)"},
  {itemLevel: 10, name: "Magic Chain Mail"},
  {itemLevel: 10, name: "Magic Leather"},
  {itemLevel: 10, name: "Magic Mace"},
  {itemLevel: 10, name: "Magic Potion"},
  {itemLevel: 10, name: "Magic Short Sword"},
  {itemLevel: 11, name: "Glacialis Scroll"},
  {itemLevel: 11, name: "Magic Battle Axe"},
  {itemLevel: 11, name: "Magic Elven Leather"},
  {itemLevel: 11, name: "Magic Regen Potion (craftable)"},
  {itemLevel: 11, name: "Magic Sword (+3 hit)"},
  {itemLevel: 11, name: "Magic Sword (1hit. 2rage)"},
  {itemLevel: 11, name: "Magic Sword (no pic yet)"},
  {itemLevel: 11, name: "Strength Amulet"},
  {itemLevel: 12, name: "Mage Magic Staff"},
  {itemLevel: 12, name: "Mage Robe"},
  {itemLevel: 12, name: "Magic Battle Hammer"},
  {itemLevel: 12, name: "Magic Elven Chain"},
  {itemLevel: 12, name: "Magic Long Bow"},
  {itemLevel: 12, name: "Magic Plate Mail"},
  {itemLevel: 12, name: "Magic Throwing Star"},
  {itemLevel: 12, name: "Magic Wolf Blades"},
  {itemLevel: 12, name: "Oak Shaft Arrows"},
  {itemLevel: 12, name: "Shon Tree Leaf"},
  {itemLevel: 13, name: "Fast Gas Form Potion (craftable)"},
  {itemLevel: 13, name: "Gas for Potion"},
  {itemLevel: 13, name: "Hazardous Liquid (craftable)"},
  {itemLevel: 13, name: "Magic Buckler"},
  {itemLevel: 13, name: "Magic Elven Helmet"},
  {itemLevel: 13, name: "Magic Elven Plate"},
  {itemLevel: 13, name: "Magic Rapier"},
  {itemLevel: 14, name: "Fire Dagger"},
  {itemLevel: 14, name: "Fire Mace (super)"},
  {itemLevel: 14, name: "Fire Mace"},
  {itemLevel: 14, name: "Fire Staff"},
  {itemLevel: 14, name: "Fire Sword"},
  {itemLevel: 14, name: "Hit Amulet (+5 to hit)"},
  {itemLevel: 14, name: "Wand of Mederi"},
  {itemLevel: 14, name: "Wand of Transport"},
  {itemLevel: 15, name: "Cape of Resistance"},
  {itemLevel: 15, name: "Cloak of Protection"},
  {itemLevel: 15, name: "Fire Sword (super)"},
  {itemLevel: 15, name: "Giant Sword (grey colour)"},
  {itemLevel: 15, name: "Giant Sword (red colour)"},
  {itemLevel: 15, name: "Hell Sword"},
  {itemLevel: 15, name: "Magic Hat"},
  {itemLevel: 15, name: "Minor Energy Ring"},
  {itemLevel: 15, name: "Minor Fire Ring"},
  {itemLevel: 15, name: "Minor Ice Ring"},
  {itemLevel: 15, name: "Minor Shadow Ring"},
  {itemLevel: 16, name: "Dragon Blades"},
  {itemLevel: 16, name: "Dragon Sword"},
  {itemLevel: 16, name: "Emerald"},
  {itemLevel: 16, name: "Fire Staff (super)"},
  {itemLevel: 16, name: "Magic 2H Sword"},
  {itemLevel: 16, name: "Magic Axe"},
  {itemLevel: 16, name: "Magic Silver Sword"},
  {itemLevel: 16, name: "Minor Spirit Ring"},
  {itemLevel: 16, name: "Red Opal"},
  {itemLevel: 17, name: "Acid Dagger"},
  {itemLevel: 17, name: "Fire Bow"},
  {itemLevel: 17, name: "Fulgar Wand"},
  {itemLevel: 17, name: "Reflective Helmet"},
  {itemLevel: 17, name: "Reflective Robe"},
  {itemLevel: 17, name: "Reflective Shield"},
  {itemLevel: 17, name: "Tueri Ring"},
  {itemLevel: 17, name: "Vis Baritus Scroll"},
  {itemLevel: 18, name: "Acid Halberd (super)"},
  {itemLevel: 18, name: "Acid Halberd"},
  {itemLevel: 18, name: "Acid Mace (energy)"},
  {itemLevel: 18, name: "Acid Mace"},
  {itemLevel: 18, name: "Acid Staff"},
  {itemLevel: 18, name: "Apprentice Energy Hat"},
  {itemLevel: 18, name: "Arcflamma Scroll"},
  {itemLevel: 18, name: "Barbed Oak Arrows"},
  {itemLevel: 18, name: "Boots of Dodging"},
  {itemLevel: 18, name: "Boots of Fortitude"},
  {itemLevel: 18, name: "Fighter Gloves"},
  {itemLevel: 18, name: "Reflective Chain"},
  {itemLevel: 18, name: "Reflective Plate"},
  {itemLevel: 18, name: "Tueri Ring (super fire)"},
  {itemLevel: 18, name: "Tueri Ring (super ice)"},
  {itemLevel: 19, name: "Acid Axe"},
  {itemLevel: 19, name: "Acid Sword"},
  {itemLevel: 19, name: "Dispell Mace"},
  {itemLevel: 19, name: "Hit Amulet (+10 to hit)"},
  {itemLevel: 19, name: "Key 1-255"},
  {itemLevel: 19, name: "Key (no green boarder)"},
  {itemLevel: 19, name: "Spirit Key (for 55/65/70 Chests)"},
  {itemLevel: 20, name: "Acid Staff (super)"},
  {itemLevel: 20, name: "Apprentice Fire Hat"},
  {itemLevel: 20, name: "Dispell Axe"},
  {itemLevel: 20, name: "Dragon Helmet"},
  {itemLevel: 20, name: "Salubris Ring (super)"},
  {itemLevel: 20, name: "Salubris Ring"},
  {itemLevel: 20, name: "Specteral Dagger"},
  {itemLevel: 20, name: "Specteral Dragon Claw"},
  {itemLevel: 20, name: "Specteral Gloves (super)"},
  {itemLevel: 20, name: "Specteral Gloves"},
  {itemLevel: 21, name: "Dragon Shield"},
  {itemLevel: 21, name: "Earth Hammer"},
  {itemLevel: 21, name: "Gloves of Strength (super)"},
  {itemLevel: 21, name: "Gloves of Strength "},
  {itemLevel: 21, name: "Specteral Mace (energy)"},
  {itemLevel: 21, name: "Specteral Mace (shadow)"},
  {itemLevel: 21, name: "Staff of Omnis"},
  {itemLevel: 22, name: "Apprentice Shadow Hat"},
  {itemLevel: 22, name: "Blood Axe"},
  {itemLevel: 22, name: "Blood Mace"},
  {itemLevel: 22, name: "Blood Rapier"},
  {itemLevel: 22, name: "Cape of Defense"},
  {itemLevel: 22, name: "Cloak of Accuracy"},
  {itemLevel: 22, name: "Magic Spiked Plate"},
  {itemLevel: 22, name: "Maximus Potion"},
  {itemLevel: 22, name: "Vorpal Battle Axe"},
  {itemLevel: 22, name: "Vorpal Scimitar"},
  {itemLevel: 22, name: "Vorpal Sword"},
  {itemLevel: 22, name: "Vorpal Wolf Blades"},
  {itemLevel: 23, name: "Ice Blade"},
  {itemLevel: 23, name: "Ice Hammer"},
  {itemLevel: 23, name: "Ice Mace"},
  {itemLevel: 23, name: "Life Hammer"},
  {itemLevel: 23, name: "Magic Bag (green background)"},
  {itemLevel: 23, name: "Magic Bag"},
  {itemLevel: 23, name: "Sanctus Scroll"},
  {itemLevel: 23, name: "Scimitar"},
  {itemLevel: 23, name: "Scroll Creare Porta"},
  {itemLevel: 24, name: "Dangerous Liquid (craftable)"},
  {itemLevel: 24, name: "Elemental Helmet"},
  {itemLevel: 24, name: "Elemental Shield"},
  {itemLevel: 24, name: "Lightning Dagger"},
  {itemLevel: 24, name: "Lightning Staff (super)"},
  {itemLevel: 24, name: "Magic Arrows"},
  {itemLevel: 24, name: "Power Potion"},
  {itemLevel: 24, name: "White Potion"},
  {itemLevel: 25, name: "Elemental Leather"},
  {itemLevel: 25, name: "Lightning Mace"},
  {itemLevel: 25, name: "Lightning Staff"},
  {itemLevel: 25, name: "Lightning Sword"},
  {itemLevel: 25, name: "Oreseth Guard Ring (ndnt pix task)"},
  {itemLevel: 25, name: "Salutaris Ring"},
  {itemLevel: 26, name: "Excelsus Shield"},
  {itemLevel: 26, name: "Fire Helmet (super)"},
  {itemLevel: 26, name: "Fire Helmet"},
  {itemLevel: 26, name: "Hit Amulet (+15 to hit)"},
  {itemLevel: 26, name: "Lightning Bow (super)"},
  {itemLevel: 26, name: "Lightning Bow"},
  {itemLevel: 26, name: "Mage Hat"},
  {itemLevel: 27, name: "Black Pearl"},
  {itemLevel: 27, name: "Bone Mace"},
  {itemLevel: 27, name: "Bone Staff (super)"},
  {itemLevel: 27, name: "Bone Staff"},
  {itemLevel: 27, name: "Elemental Chain"},
  {itemLevel: 27, name: "Excelsus Shield (super)"},
  {itemLevel: 27, name: "Gloves of Skill"},
  {itemLevel: 27, name: "Mage Hate (super)"},
  {itemLevel: 27, name: "Maximus Amulet"},
  {itemLevel: 28, name: "Animus Ring"},
  {itemLevel: 28, name: "Dragon Boots"},
  {itemLevel: 28, name: "Runic Mace"},
  {itemLevel: 28, name: "Runic Scimitar"},
  {itemLevel: 28, name: "Sanctus Axe"},
  {itemLevel: 28, name: "Sanctus Blade"},
  {itemLevel: 28, name: "Sanctus Mace"},
  {itemLevel: 28, name: "Sanctus Shield"},
  {itemLevel: 28, name: "Velocitas Ring"},
  {itemLevel: 29, name: "Elemental Plate"},
  {itemLevel: 29, name: "Green Elixir"},
  {itemLevel: 29, name: "Lucrum Animus Staff (super)"},
  {itemLevel: 29, name: "Lucrum Animus Staff "},
  {itemLevel: 29, name: "Runic Scimitar (super)"},
  {itemLevel: 29, name: "Runic Staff (energy ice)"},
  {itemLevel: 29, name: "Runic Staff (fire shadow)"},
  {itemLevel: 29, name: "Runic Staff (ice spirit)"},
  {itemLevel: 29, name: "Runic Staff (shadow spirit)"},
  {itemLevel: 29, name: "Sanctus Shield (super)"},
  {itemLevel: 30, name: "Barbed Magic Arrows"},
  {itemLevel: 30, name: "Blue Elixir"},
  {itemLevel: 30, name: "Mage Gloves"},
  {itemLevel: 30, name: "Mystic Helmet (super)"},
  {itemLevel: 30, name: "Mystic Helmet"},
  {itemLevel: 30, name: "Mystic Rapier"},
  {itemLevel: 30, name: "Mystic Shield"},
  {itemLevel: 30, name: "Reditus Amulet"},
  {itemLevel: 31, name: "Energy Robe"},
  {itemLevel: 31, name: "Holy Mystic Helmet"},
  {itemLevel: 31, name: "Lucranimus Ring"},
  {itemLevel: 31, name: "Mystic Dagger"},
  {itemLevel: 31, name: "Mystic Leather"},
  {itemLevel: 31, name: "Mystic Plate"},
  {itemLevel: 31, name: "Mystic Short Sword"},
  {itemLevel: 31, name: "Mystic Staff"},
  {itemLevel: 31, name: "Shadow Robe"},
  {itemLevel: 31, name: "Spirit Robe"},
  {itemLevel: 32, name: "Mystic Battle Axe (super)"},
  {itemLevel: 32, name: "Mystic Battle Axe"},
  {itemLevel: 32, name: "Mystic Cloak"},
  {itemLevel: 32, name: "Mystic Mace"},
  {itemLevel: 32, name: "Mystic Plate (super)"},
  {itemLevel: 32, name: "Mystic Sword"},
  {itemLevel: 32, name: "Mystic Wolf Blades (super)"},
  {itemLevel: 32, name: "Mystic Wolf Blades"},
  {itemLevel: 32, name: "Scientia Ring"},
  {itemLevel: 33, name: "Adept Hat"},
  {itemLevel: 33, name: "Black Dragon Helmet"},
  {itemLevel: 33, name: "Mystic Bow"},
  {itemLevel: 33, name: "Scientia Ring (+2)"},
  {itemLevel: 33, name: "Staff of Vis Omnis"},
  {itemLevel: 33, name: "Vis Mederi Ring"},
  {itemLevel: 33, name: "Vis Tueri Ring"},
  {itemLevel: 33, name: "Vitadimere Halberd"},
  {itemLevel: 33, name: "Vitadimere Rapier"},
  {itemLevel: 34, name: "Apprentice Fighter Ring"},
  {itemLevel: 34, name: "Apprentice Mage Ring"},
  {itemLevel: 34, name: "Mystic Bow (super)"},
  {itemLevel: 34, name: "Mystic War Mace"},
  {itemLevel: 35, name: "Gloves of Rage"},
  {itemLevel: 35, name: "Mystic Hat"},
  {itemLevel: 35, name: "Mystic Shield (super)"},
  {itemLevel: 35, name: "Staff of Almus"},
  {itemLevel: 35, name: "Sworf of the Dead"},
  {itemLevel: 35, name: "Vis Animus Ring"},
  {itemLevel: 36, name: "Dentibus Mace"},
  {itemLevel: 36, name: "Mystic Arrows"},
  {itemLevel: 36, name: "Oreseth Claymore"},
  {itemLevel: 36, name: "Staff of Viarum"},
  {itemLevel: 36, name: "Vis Velocitas Ring"},
  {itemLevel: 37, name: "Arcane Axe"},
  {itemLevel: 37, name: "Arcane Bow"},
  {itemLevel: 37, name: "Arcane Halberd"},
  {itemLevel: 37, name: "Arcane Staff"},
  {itemLevel: 37, name: "Oreseth Halberd"},
  {itemLevel: 38, name: "Arcane Boots"},
  {itemLevel: 38, name: "Arcane Bow (super)"},
  {itemLevel: 38, name: "Arcane Hat"},
  {itemLevel: 38, name: "Arcane Robe"},
  {itemLevel: 38, name: "Arcane Sword"},
  {itemLevel: 38, name: "Fighter Boots"},
  {itemLevel: 38, name: "Life Hammer (super)"},
  {itemLevel: 38, name: "Mystic Throwing Star"},
  {itemLevel: 38, name: "Spirit Shield"},
  {itemLevel: 38, name: "White Elixir"},
  {itemLevel: 39, name: "Black Sapphire"},
  {itemLevel: 39, name: "Spirit Helmet (super)"},
  {itemLevel: 39, name: "Spirit Helmet"},
  {itemLevel: 39, name: "Spirit Shield (super)"},
  {itemLevel: 40, name: "Arcane Hat (super energy/spirit)"},
  {itemLevel: 40, name: "Arcane Staff (super)"},
  {itemLevel: 40, name: "Dentibus Mace (super)"},
  {itemLevel: 40, name: "Holy Spirit Helmet"},
  {itemLevel: 40, name: "Oreseth Claymore (super)"},
  {itemLevel: 40, name: "Spirit Leather"},
  {itemLevel: 40, name: "Warrior Gloves"},
  {itemLevel: 41, name: "Spirit Bow"},
  {itemLevel: 41, name: "Spirit Staff"},
  {itemLevel: 42, name: "Arcane Axe (super)"},
  {itemLevel: 42, name: "Cape of Fortitude"},
  {itemLevel: 42, name: "Nex Arrows"},
  {itemLevel: 42, name: "Spirit Leather (super)"},
  {itemLevel: 43, name: "Spirit Blades"},
  {itemLevel: 43, name: "Spirit Plate"},
  {itemLevel: 43, name: "Staff of Almus (super)"},
  {itemLevel: 44, name: "Diamond"},
  {itemLevel: 44, name: "Spirit Leather (super super)"},
  {itemLevel: 44, name: "Spirit Wolf Blades (super)"},
  {itemLevel: 44, name: "Staff of Viarum (super)"},
  {itemLevel: 45, name: "Bow of Torment"},
  {itemLevel: 45, name: "Fighter Ring"},
  {itemLevel: 45, name: "Gloves of Lethal Rage"},
  {itemLevel: 45, name: "Mage Ring"},
  {itemLevel: 45, name: "Mystic Bone Mail"},
  {itemLevel: 45, name: "Spirit Dagger"},
  {itemLevel: 45, name: "Spirit Sword"},
  {itemLevel: 45, name: "Spirit War Hammer"},
  {itemLevel: 46, name: "Arcane Hat (super fire ice)"},
  {itemLevel: 46, name: "Mystic Bone Staff"},
  {itemLevel: 46, name: "Mystic Bone Sword"},
  {itemLevel: 47, name: "Mystic Bone Shield"},
  {itemLevel: 47, name: "Spirit Plate (super)"},
  {itemLevel: 48, name: "Arcane Robe (super)"},
  {itemLevel: 48, name: "Spirit Boots"},
  {itemLevel: 48, name: "Spirit Staff (super)"},
  {itemLevel: 50, name: "Axe of Torment"},
  {itemLevel: 50, name: "Bow of Torment (super)"},
  {itemLevel: 50, name: "Chain of Torment"},
  {itemLevel: 50, name: "Gloves of Imexic (ndnt boss item)"},
  {itemLevel: 50, name: "Helm of Torment"},
  {itemLevel: 50, name: "Mystic Blade"},
  {itemLevel: 50, name: "Spirit Wand"},
  {itemLevel: 50, name: "Staff of Torment"},
  {itemLevel: 50, name: "War Mace of Torment"},
  {itemLevel: 52, name: "Arcane Hat (super shadow fire)"},
  {itemLevel: 52, name: "Dragon Cloak"},
  {itemLevel: 52, name: "Gloves of Imexic (super ndnt boss item)"},
  {itemLevel: 52, name: "Mystic Bone Staff (super fire)"},
  {itemLevel: 52, name: "Mystic Bone Staff (super shadow)"},
  {itemLevel: 53, name: "Shadow Blade"},
  {itemLevel: 53, name: "Spirit Ripper"},
  {itemLevel: 54, name: "Black Dragon Bow"},
  {itemLevel: 54, name: "Black Dragon Shield"},
  {itemLevel: 54, name: "Leather of Torment"},
  {itemLevel: 54, name: "Spirit Mace"},
  {itemLevel: 55, name: "Derath's Ring"},
  {itemLevel: 55, name: "Dragon Lord Staff"},
  {itemLevel: 55, name: "Hammer of Torment"},
  {itemLevel: 55, name: "Volcanic Dagger"},
  {itemLevel: 55, name: "War Mace of Torment (super)"},
  {itemLevel: 56, name: "Spiritus Ring"},
  {itemLevel: 56, name: "Sword of Blood"},
  {itemLevel: 57, name: "Black Dragon Sword"},
  {itemLevel: 57, name: "Derath's Ring (super)"},
  {itemLevel: 57, name: "Ice Dragon Staff"},
  {itemLevel: 58, name: "Adept Robe"},
  {itemLevel: 58, name: "Boots of Torment"},
  {itemLevel: 58, name: "Glowing Potion"},
  {itemLevel: 59, name: "Axe of Havoc"},
  {itemLevel: 60, name: "Adept Magus Hat"},
  {itemLevel: 60, name: "Altus Lucrum Staff"},
  {itemLevel: 60, name: "Baraw's Dragon Helm (ndnt boss item)"},
  {itemLevel: 60, name: "Demonic Leather"},
  {itemLevel: 60, name: "Demonic War Hammer"},
  {itemLevel: 60, name: "Havoc Blades"},
  {itemLevel: 60, name: "Spirit Wand (super)"},
  {itemLevel: 61, name: "Ominex Rapier (super)"},
  {itemLevel: 61, name: "Sword of Evil"},
  {itemLevel: 62, name: "Adept Cape"},
  {itemLevel: 62, name: "Adept Magus Gloves"},
  {itemLevel: 62, name: "Baraw's Draon Helm (super ndnt boss item)"},
  {itemLevel: 62, name: "Demonic Cloak"},
  {itemLevel: 63, name: "Ominex Rapier"},
  {itemLevel: 63, name: "Volcanic Sword"},
  {itemLevel: 64, name: "Volcanic Shield"},
  {itemLevel: 65, name: "Adept Magus Hat (super)"},
  {itemLevel: 65, name: "Demonic Axe"},
  {itemLevel: 65, name: "Havoc Bow (super)"},
  {itemLevel: 65, name: "Shield of Ominex"},
  {itemLevel: 65, name: "Sogam's Hat (ndnt boss item)"},
  {itemLevel: 65, name: "Staff of Ominex"},
  {itemLevel: 66, name: "Ominex Claymore"},
  {itemLevel: 66, name: "Ominex Dagger"},
  {itemLevel: 66, name: "Shield of Ominex (super)"},
  {itemLevel: 66, name: "Skull Crusher"},
  {itemLevel: 67, name: "Ominex Warrior Gloves"},
  {itemLevel: 67, name: "Ominex Wolf Blades"},
  {itemLevel: 67, name: "Sword of Ominex"},
  {itemLevel: 67, name: "Sogam's Hat (super ndnt boss item)"},
  {itemLevel: 68, name: "Adept Robe (super)"},
  {itemLevel: 68, name: "Helmet of Ominex (super)"},
  {itemLevel: 68, name: "Helmet of Ominex"},
  {itemLevel: 68, name: "Ominex Boots"},
  {itemLevel: 68, name: "Sword of Ominex (super)"},
  {itemLevel: 68, name: "Volcanic Shield (super)"},
  {itemLevel: 69, name: "Demon Eye Staff"},
  {itemLevel: 69, name: "Hammer of Ominex"},
  {itemLevel: 70, name: "Axe oof Ominex"},
  {itemLevel: 70, name: "Demonic Chain"},
  {itemLevel: 70, name: "Dirus Wand"},
  {itemLevel: 70, name: "Holy Ominex Helmet"},
  {itemLevel: 70, name: "Master Fighter Ring"},
  {itemLevel: 70, name: "Master Mage Ring"},
  {itemLevel: 70, name: "Ominex War Hammer"},
  {itemLevel: 70, name: "Shroud Gloves"},
  {itemLevel: 70, name: "Tritoon Shield"},
  {itemLevel: 71, name: "Bow of Ominex (super)"},
  {itemLevel: 71, name: "Bow of Ominex"},
  {itemLevel: 72, name: "Gray Shroud"},
  {itemLevel: 72, name: "Ominex Cape"},
  {itemLevel: 72, name: "Ominex War Sword"},
  {itemLevel: 72, name: "Omni Shield of Elements"},
  {itemLevel: 73, name: "Leather of Ominex"},
  {itemLevel: 74, name: "Diabolic Mace"},
  {itemLevel: 74, name: "Diabolic Rapier"},
  {itemLevel: 74, name: "Staff of Ominex (super)"},
  {itemLevel: 75, name: "Demonic Bow"},
  {itemLevel: 75, name: "Diabolic Helmet"},
  {itemLevel: 75, name: "Diabolic Wolf Blades"},
  {itemLevel: 75, name: "Diabolic Wolf Blades (super by 2 more lethal, pointless item i think is corrupted arachnid wolf blades?)"},
  {itemLevel: 75, name: "Shroud Axe"},
  {itemLevel: 76, name: "Gray Shroud (super)"},
  {itemLevel: 76, name: "Omni Shield of Elements (super)"},
  {itemLevel: 77, name: "Shroud Hat"},
  {itemLevel: 77, name: "Zon Rin's Leather (super ndnt boss item)"},
  {itemLevel: 78, name: "Diabolic Boots"},
  {itemLevel: 78, name: "Diabolic Staff"},
  {itemLevel: 78, name: "Leather of Ominex (super)"},
  {itemLevel: 78, name: "Moon Robe"},
  {itemLevel: 79, name: "Diabolic Plate"},
  {itemLevel: 79, name: "Diabolic Scimitar"},
  {itemLevel: 80, name: "Adept Ring"},
  {itemLevel: 80, name: "Arachnid Blade (ndnt boss item)"},
  {itemLevel: 80, name: "Arachnid Bow (ndnt boss item)"},
  {itemLevel: 80, name: "Arachnid Carapace (ndnt boss item)"},
  {itemLevel: 80, name: "Arachnid Eye (ndnt boss item)"},
  {itemLevel: 80, name: "Arachnid Mace (ndnt boss item)"},
  {itemLevel: 80, name: "Arachnid Shield (ndnt boss item)"},
  {itemLevel: 80, name: "Arachnid Staff (ndnt boss item)"},
  {itemLevel: 80, name: "Diabolic Hammer"},
  {itemLevel: 80, name: "Diabolic Shield"},
  {itemLevel: 80, name: "Diabolic Wand"},
  {itemLevel: 80, name: "Warrior Ring"},
  {itemLevel: 81, name: "Dirus Battle Axe"},
  {itemLevel: 81, name: "Dirus Rapier"},
  {itemLevel: 81, name: "Optimus Magus Staff"},
  {itemLevel: 82, name: "Dirus Bow"},
  {itemLevel: 82, name: "Dirus Cloak"},
  {itemLevel: 82, name: "Havoc War Sword"},
  {itemLevel: 82, name: "Holy Power Shield"},
  {itemLevel: 83, name: "Bow of Lethal Speed"},
  {itemLevel: 83, name: "Dirus Bow (super)"},
  {itemLevel: 84, name: "Bow of Lethal Speed (super)"},
  {itemLevel: 84, name: "Dirus Chain"},
  {itemLevel: 85, name: "Adept Ring (super)"},
  {itemLevel: 85, name: "Demonic Helmet"},
  {itemLevel: 85, name: "Diabolic Shield (super)"},
  {itemLevel: 85, name: "Diabolic Staff (super)"},
  {itemLevel: 85, name: "Dirus Wand (super)"},
  {itemLevel: 85, name: "Shroud Hat"},
  {itemLevel: 85, name: "Triton Battle Axe"},
  {itemLevel: 85, name: "Triton Dagger"},
  {itemLevel: 85, name: "Triton Halberd"},
  {itemLevel: 85, name: "Triton War Sword"},
  {itemLevel: 85, name: "Warrior Ring (super)"},
  {itemLevel: 86, name: "Shroud Gloves (super)"},
  {itemLevel: 86, name: "Triton Bow"},
  {itemLevel: 86, name: "Triton Wolf Blades"},
  {itemLevel: 87, name: "Blood Shadow Blade"},
  {itemLevel: 88, name: "Shroud Boots"},
  {itemLevel: 90, name: "Cron's Adept Ring (ndnt boss item)"},
  {itemLevel: 90, name: "Cron's Gloves (ndnt boss item)"},
  {itemLevel: 90, name: "Cron's Tail Dagger (ndnt boss item)"},
  {itemLevel: 90, name: "Cron's Tail Wand (ndnt boss item)"},
  {itemLevel: 90, name: "Cron's Warrior Ring (ndnt boss item)"},
  {itemLevel: 90, name: "Death Knight Sword"},
  {itemLevel: 90, name: "Diabolic Magus Staff"},
  {itemLevel: 90, name: "Dirus Hammer"},
  {itemLevel: 90, name: "Holy Crystal Shield"},
  {itemLevel: 90, name: "Omni Spiritus Ring"},
  {itemLevel: 91, name: "Fragor Mace"},
];
